### ISSUE TITLE
Unable to install certificate.

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh-in-a-box#2]
I believe this is a nosh-in-a-box related issue.

I've done a completely new install of nosh-in-a-box to ensure that everything is set up correctly with static IPs and all that stuff that has been giving me trouble.

I've entered my domain during the initial installation and it proceeds to communicate with letsencrypt to install the certificate.

Twice I've done this and ended up with the same error. After a successful communication and key generation I am told "Unable to install the certificate". There is an error message about "Unsupported filesystem layout. sites-available/enabled expected."

Screenshot attached for full terminal error.
![letsencrypt](https://cloud.githubusercontent.com/assets/26801488/24572734/e97240e2-1627-11e7-8e4e-8b3694e8dc9e.png)

**Comment by rumsant** [comment]
I deleted the /etc/letsencrypt directory that was created and proceeded to use "install-ssl" and that worked, but I had to stop apache2 first.

**Comment by shihjay2** [comment]
Fixed in commit 00570a98e03f9d825dc61b0758207cd3da41babe
