### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh-in-a-box#9]
Today when I tried to vagrant ssh into the machine, I was asked for a password, which has never happened before. I tried every password I could think of, but nothing worked.

I decided to vagrant halt and just restart the machine, but now when the machine starts, I get "Warning: Authentication failre. Retrying...".

The machine apparently starts up because I'm able to access Nosh, but what I can't do is vagrant ssh into the system. I've tried to figure out what might be going on, and it seems like it might have something to do with private or public keys, but I don't really understand that stuff.

The only thing that has changed prior to this happening was a normal update of the Ubuntu host operating system last Friday. I don't know if that changed some files or permissions or something, but I thought I'd ask you here in case it's something simple that I'm missing.

Thank you.

**Comment by shihjay2** [comment]
I don't know if you have tried the solution in [this link](http://www.gisremotesensing.com/2016/06/solution-vagrant-box-authentication.html).  It may be worth a shot as it might have been related to the Ubuntu update regarding SSH and VirtualBox that might be the issue.

**Comment by rumsant** [comment]
I wanted to try the solution you linked above, but when I vagrant ssh and try to use what is purported to be the default password "vagrant" it doesn't work and I'm not able to login and perform the following actions.

I reinstalled again, and the first time I installed I was able to vagrant ssh like normal, but after having done a vagrant halt and restarting with a vagrant up, the same problem manifested: "Warning: Authentication failre. Retrying...".

Do you think this could have anything to do with the fact that I'm using Ubuntu 18.04.1 LTS?

**Comment by rumsant** [comment]
I was able to follow the solution that you linked to by starting Nosh with the gui from virtualbox and logging in that way, but unfortunately I am having the same authentication issue.

**Comment by shihjay2** [comment]
Consider reviewing this page (especially at the bottom where they talking
about vagrant ssh-config and see if that can help your issue.
http://www.codebind.com/linux-tutorials/install-vagrant-ubuntu-18-04-lts-linux/

**Comment by rumsant** [comment]
I was unable to solve this problem, but after a second reinstall and restore, the problem does not seem to be occurring again.
